<?php

namespace Modules\Asistencia\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SegundaEspecialidadSeeder extends Seeder
{
    public function run()
    {
        // 1. Listado depurado de duplicados ortográficos y normalizado
        $especialidadesRaw = [
            'ADMINISTRACIÓN DE HOSPITALES',
            'ADMINISTRACIÓN DE SALUD',
            'ADMINISTRACIÓN EN RECURSOS HUMANOS',
            'ADMINISTRACION FARMACEUTICA',
            'ADMINISTRACIÓN SOCIAL',
            'ADMINISTRACIÓN Y GERENCIA EN SALUD',
            'ADMINISTRACIÓN Y GESTIÓN EN ESTOMATOLOGÍA',
            'ADMINISTRACIÓN Y GESTIÓN EN SALUD',
            'ADOLESCENTOLOGÍA',
            'ALERGIA E INMUNOLOGÍA CLÍNICA PEDIÁTRICA',
            'ALERGIA E INMUNOPATOLOGÍA',
            'ALERGOLOGÍA',
            'ALTO RIESGO OBSTÉTRICO',
            'ANÁLISIS CLÍNICOS',
            'ANATOMÍA HUMANA',
            'ANATOMÍA PATOLÓGICA',
            'ANATOMÍA PATOLÓGICA - PATOLOGÍA CLÍNICA',
            'ANATOMÍA PATOLÓGICA Y LABORATORIO',
            'ANESTESIA, ANALGESIA Y REANIMACIÓN',
            'ANESTESIOLOGÍA',
            'ANESTESIOLOGÍA CARDIOVASCULAR',
            'ANESTESIOLOGÍA OBSTÉTRICA',
            'ANESTESIOLOGÍA Y CUIDADOS INTENSIVOS',
            'ANESTESIOLOGÍA Y REANIMACIÓN',
            'ANESTESIOLOGÍA Y TERAPIA INTENSIVA CARDIOVASCULAR',
            'ANGIOLOGÍA',
            'APARATO DIGESTIVO',
            'ARTROSCOPIA Y CIRUGÍA DE RODILLA',
            'ASESORÍA GENÉTICA EN ENFERMERÍA ONCOLÓGICA',
            'ATENCION INTEGRAL EN EL ADULTO MAYOR',
            'ATENCION OBSTETRICA DE LA EMERGENCIA Y CUIDADOS CRITICOS',
            'ATENCION PRIMARIA DE SALUD',
            'AUDITORIA ODONTOLÓGICA',
            'BIOLOGÍA DE LA REPRODUCCIÓN HUMANA',
            'BIOLOGÍA FORENSE',
            'BIOLOGÍA MOLECULAR Y GENÉTICA',
            'BIOQUÍMICA CLÍNICA',
            'BROMATOLOGIA',
            'CALIDAD Y AUDITORÍA DE LOS SERVICIOS DE SALUD',
            'CARDIOLOGÍA',
            'CARDIOLOGÍA INFANTIL',
            'CARDIOLOGÍA INTERVENCIONISTA Y HEMODINÁMICA',
            'CARDIOLOGÍA PEDIÁTRICA',
            'CASA DE REHABILITACIÓN',
            'CENTRO QUIRÚRGICO',
            'CIRUGÍA AORTICA',
            'CIRUGÍA BUCAL Y MAXILOFACIAL',
            'CIRUGÍA CARDIOVASCULAR',
            'CIRUGÍA CARDIOVASCULAR PEDIÁTRICA',
            'CIRUGÍA COLORRECTAL',
            'CIRUGÍA CRANEOMAXILOFACIAL',
            'CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL',
            'CIRUGÍA DE CABEZA Y CUELLO',
            'CIRUGÍA DE COLON, RECTO Y ANO',
            'CIRUGÍA DE LA RODILLA',
            'CIRUGÍA DE MANO',
            'CIRUGÍA DE RETINA Y VITREO',
            'CIRUGÍA DE TÓRAX',
            'CIRUGÍA DE TÓRAX ONCOLÓGICA',
            'CIRUGÍA ENDOSCÓPICA GINECOLÓGICA',
            'CIRUGÍA GASTROENTEROLÓGICA',
            'CIRUGÍA GENERAL',
            'CIRUGÍA GENERAL Y DEL APARATO DIGESTIVO',
            'CIRUGÍA GENERAL Y ONCOLÓGICA',
            'CIRUGÍA HEPATOPANCREATOBILIAR Y TRASPLANTE',
            'CIRUGÍA HOSPITALARIA',
            'CIRUGÍA NEUMOLÓGICA',
            'CIRUGÍA ONCOLÓGICA',
            'CIRUGÍA ONCOLÓGICA ABDOMINAL',
            'CIRUGÍA ONCOLÓGICA DE CABEZA Y CUELLO',
            'CIRUGÍA ONCOLÓGICA DE MAMAS, TEJIDOS BLANDOS Y PIEL',
            'CIRUGÍA ORTOPÉDICA Y TRAUMATOLOGÍA',
            'CIRUGÍA PEDIÁTRICA',
            'CIRUGÍA PLÁSTICA',
            'CIRUGÍA PLÁSTICA FACIAL',
            'CIRUGÍA PLÁSTICA Y CAUMATOLOGÍA',
            'CIRUGÍA PLÁSTICA Y ESTÉTICA',
            'CIRUGÍA PLÁSTICA Y RECONSTRUCTIVA',
            'CIRUGÍA PLÁSTICA Y REPARADORA',
            'CIRUGÍA RECONSTRUCTIVA Y DEL REEMPLAZO ARTICULAR DE CADERA Y DE RODILLA',
            'CIRUGÍA TORÁCICA Y CARDIOVASCULAR',
            'CIRUGÍA, TRANSPLANTOLOGÍA Y ANDROLOGÍA',
            'CIRUGÍA VASCULAR PERIFÉRICA',
            'COLOPROCTOLOGÍA',
            'CONSEJERÍA Y BIENESTAR SOCIAL',
            'CONSEJERÍA Y MEDITACIÓN',
            'CONTAMINACIÓN Y GESTIÓN AMBIENTAL',
            'CUIDADO DE LA PERSONA EN INFECTOLOGÍA',
            'CUIDADO ENFERMERO EN CARDIOLOGIA Y CARDIOVASCULAR',
            'CUIDADO ENFERMERO EN EMERGENCIA Y DESASTRES',
            'CUIDADO ENFERMERO EN NEONATOLOGIA',
            'CUIDADO ENFERMERO EN ONCOLOGIA',
            'CUIDADO INTEGRAL INFANTIL',
            'CUIDADOS ALTERNATIVOS Y COMPLEMENTARIOS',
            'CUIDADOS EN RADIOLOGÍA INTERVENCIONISTA',
            'CUIDADOS PALIATIVOS',
            'CUIDADOS PARA LA SALUD DEL ADULTO',
            'CUIDADOS QUIRÚRGICOS',
            'DERECHO DE FAMILIA',
            'DERECHOS HUMANOS',
            'DERMATOLOGÍA PEDIÁTRICA',
            'DERMATOLOGÍA Y VENEREOLOGÍA',
            'DIABETOLOGÍA',
            'DIAGNÓSTICO POR IMÁGENES',
            'DISCAPACIDAD',
            'DISEÑO, GESTIÓN Y MONITOREO DE PROYECTOS SOCIALES',
            'DOCENCIA EN ENFERMERÍA',
            'DOCENCIA UNIVERSITARIA E INVESTIGACIÓN',
            'EDUCACIÓN SEXUAL Y SALUD REPRODUCTIVA',
            'ELECTROFISIOLOGÍA CARDIACA CLÍNICA',
            'ELECTROFISIOLOGÍA CARDIOVASCULAR',
            'EMBRIOLOGÍA',
            'EMERGENCIA OBSTÉTRICAS Y CUIDADOS CRÍTICOS',
            'EMERGENCIAS PEDIÁTRICAS',
            'ENDOCRINOLOGÍA PEDIÁTRICA',
            'ENDOCRINOLOGÍA Y ENFERMEDADES METABÓLICAS',
            'ENDOCRINOLOGÍA Y NUTRICIÓN',
            'ENDODONCIA',
            'ENFERMEDADES INFECCIOSAS Y TROPICALES',
            'ENFERMERA ESPECIALISTA EN CUIDADOS INTENSIVOS',
            'ENFERMERA ESPECIALISTA EN SALUD PÚBLICA CON MENCIÓN EN CRECIMIENTO Y DESARROLLO',
            'ENFERMERÍA CARDIOLÓGICA',
            'ENFERMERIA CENTRO QUIRURGICO Y CENTRAL DE ESTERILIZACION',
            'ENFERMERIA CUIDADOS EN EMERGENCIAS Y DESASTRES',
            'ENFERMERIA CUIDADOS INTENSIVOS PEDIATRICOS',
            'ENFERMERIA DE CUIDADOS NEONATALES',
            'ENFERMERIA DEL CUIDADO DEL PACIENTE CRITICO NEONATAL',
            'ENFERMERÍA EN CIRUGÍA CARDIOVASCULAR',
            'ENFERMERÍA EN CIRUGÍA GENERAL Y ESPECIALIDADES',
            'ENFERMERÍA EN CRECIMIENTO Y DESARROLLO INFANTIL Y ESTIMULACIÓN TEMPRANA',
            'ENFERMERIA EN CUIDADO DEL NEONATO EN TERAPIA INTENSIVA',
            'ENFERMERÍA EN CUIDADOS CRÍTICOS',
            'ENFERMERIA EN CUIDADOS INTENSIVOS-ADULTO',
            'ENFERMERIA EN CUIDADOS NEFROLOGICOS',
            'ENFERMERIA EN EL CUIDADO DEL PACIENTE CRITICO ADULTO',
            'ENFERMERIA EN SALA DE RECUPERACION POSANESTESICA',
            'ENFERMERÍA EN SALUD DEL ADOLESCENTE',
            'ENFERMERÍA EN SALUD FAMILIAR Y COMUNITARIA',
            'ENFERMERÍA EN SALUD MENTAL Y PSIQUIATRÍA',
            'ENFERMERIA EN SALUD OCUPACIONAL',
            'ENFERMERÍA FORENSE',
            'ENFERMERIA GERENCIA EN SERVICIOS DE LA SALUD',
            'ENFERMERÍA GERIÁTRICA Y GERONTOLÓGICA',
            'ENFERMERÍA GINECO OBSETRICIA',
            'ENFERMERÍA MATERNO INFANTIL',
            'ENFERMERÍA NEFROLÓGICA Y UROLÓGICA',
            'ENFERMERÍA ONCOLÓGICA',
            'ENFERMERÍA PEDIÁTRICA',
            'ENTOMOLOGÍA MÉDICA Y CONTROL DE VECTORES',
            'EPIDEMIOLOGIA DE CAMPO',
            'EPIDEMIOLOGIA DE ENFERMEDADES METAXÉNICAS',
            'EPIDEMIOLOGÍA SOCIAL',
            'ESTOMATOLOGÍA DE PACIENTES ESPECIALES',
            'EVALUACIÓN Y ACREDITACIÓN DE ESTABLECIMIENTO DE SALUD',
            'FARMACIA CLÍNICA',
            'FARMACIA COMUNITARIA',
            'FARMACIA HOSPITALARIA',
            'FARMACOLOGÍA',
            'FERTILIDAD Y REPRODUCCIÓN',
            'FISIATRÍA',
            'FISIOLOGÍA',
            'FLEBOLOGÍA Y LINFOLOGÍA',
            'FONIATRÍA',
            'GASTROENTEROLOGÍA Y PROCEDIMIENTO ENDOSCÓPICOS',
            'GASTROENTEROLOGÍA PEDIÁTRICA',
            'GENÉTICA MÉDICA',
            'GERENCIA DE LA SALUD OCUPACIONAL',
            'GERENCIA EN SERVICIOS DE SALUD',
            'GERENCIA SOCIAL',
            'GERIATRÍA',
            'GERONTOLOGÍA SOCIAL',
            'GESTIÓN AMBIENTAL',
            'GESTIÓN DE CENTRAL DE ESTERILIZACIÓN',
            'GESTIÓN DE LA CALIDAD E INOCUIDAD ALIMENTARIA',
            'GESTIÓN DE NEGOCIOS EN NUTRICIÓN',
            'GESTIÓN DE RECURSOS HUMANOS EN LAS ORGANIZACIONES',
            'GESTIÓN EN SALUD',
            'GESTIÓN ESTRATÉGICA DE TRABAJO SOCIAL',
            'GESTIÓN FARMACEUTICA',
            'GESTIÓN PÚBLICA',
            'GESTION Y ADMINISTRACION EN LOS SERVICIOS DE SALUD SEXUAL Y REPRODUCTIVA',
            'GINECOLOGÍA DE LA NIÑA Y ADOLESCENTE',
            'GINECOLOGÍA ONCOLÓGICA',
            'GINECOLOGÍA Y OBSTETRICIA',
            'HEMATOLOGÍA CLÍNICA',
            'HEMATOLOGÍA PEDIÁTRICA',
            'HEMATOLOGÍA Y HEMOTERAPIA',
            'HEMODINÁMICA Y CARDIOLOGÍA INTERVENCIONISTA',
            'HEMOTERAPIA Y BANCO DE SANGRE',
            'HEPATOLOGÍA',
            'HIGIENE OCUPACIONAL',
            'HISTOPATOLOGÍA',
            'IMPLANTOLOGIA',
            'INDUSTRIA FARMACEUTICA',
            'INFECTOLOGÍA PEDIÁTRICA',
            'INGENIERÍA BIOTECNOLÓGICA MOLECULAR',
            'INMUNOHEMATOLOGIA',
            'INMUNOLOGÍA CLÍNICA Y ALERGOLOGÍA',
            'INMUNOLOGÍA Y REUMATOLOGÍA',
            'INVESTIGACIÓN EN SALUD',
            'LABORATORIO CLÍNICO Y ANATOMÍA PATOLÓGICA',
            'LABORATORIO DE ANÁLISIS CLÍNICO Y BIOLÓGICO',
            'LACTANCIA MATERNA',
            'MASTOLOGÍA',
            'MEDICINA AEROESPACIAL',
            'MEDICINA BIOLÓGICA',
            'MEDICINA CRÍTICA Y TERAPIA INTENSIVA',
            'MEDICINA DE EMERGENCIAS Y DESASTRES',
            'MEDICINA DE ENFERMEDADES INFECCIOSAS Y TROPICALES',
            'MEDICINA DEL DEPORTE',
            'MEDICINA DEL TRABAJO',
            'MEDICINA ESTÉTICA',
            'MEDICINA FAMILIAR Y COMUNITARIA',
            'MEDICINA FÍSICA Y REHABILITACIÓN',
            'MEDICINA GENERAL INTEGRAL',
            'MEDICINA HIPERBÁRICA Y SUBACUÁTICA',
            'MEDICINA INTEGRAL Y GESTIÓN EN SALUD',
            'MEDICINA INTENSIVA PEDIÁTRICA',
            'MEDICINA INTENSIVA Y DE EMERGENCIA',
            'MEDICINA INTERNA',
            'MEDICINA INTERNA - GASTROENTEROLOGÍA',
            'MEDICINA INTERNA Y CARDIOLOGÍA',
            'MEDICINA LEGAL',
            'MEDICINA MATERNO FETAL',
            'MEDICINA NUCLEAR',
            'MEDICINA OCUPACIONAL Y MEDIO AMBIENTE',
            'MEDICINA ONCOLÓGICA',
            'MEDICINA PREVENTIVA Y SALUD PUBLICA',
            'MEDICINA Y PATOLOGÍA ESTOMATOLÓGICA',
            'MICROBIOLOGÍA CLÍNICA',
            'MICROBIOLOGÍA Y PARASITOLOGÍA',
            'MICROCIRUGÍA',
            'MONITOREO FETAL Y DIAGNOSTICO POR IMÁGENES EN OBSTETRICIA',
            'NEFROLOGÍA PEDIÁTRICA',
            'NEONATOLOGÍA',
            'NEUMOLOGÍA CLÍNICA',
            'NEUMOLOGÍA ONCOLÓGICA',
            'NEUMOLOGÍA PEDIÁTRICA',
            'NEUMOLOGÍA Y TISIOLOGÍA',
            'NEUROCIRUGÍA PEDIÁTRICA',
            'NEUROFISIOLOGÍA CLÍNICA',
            'NEUROFTALMOLOGÍA',
            'NEUROLOGÍA PEDIÁTRICA',
            'NEUROPSICOLOGÍA INFANTIL Y APRENDIZAJE',
            'NEURORRADIOLOGÍA',
            'NUTRICIÓN CLÍNICA CON MENCIÓN EN NUTRICION ONCOLOGICA',
            'NUTRICIÓN DEPORTIVA',
            'NUTRICIÓN PÚBLICA',
            'OBSTETRICIA CON MENCIÓN EN EMERGENCIAS OBSTÉTRICAS, ALTO RIESGO Y CUIDADOS CRÍTICOS MATERNOS',
            'ODONTOGERIATRÍA',
            'ODONTOLOGÍA FORENSE',
            'ODONTOLOGÍA RESTAURADORA Y ESTÉTICA',
            'ODONTOPEDIATRÍA',
            'OFTALMOLOGÍA ONCOLÓGICA',
            'OFTALMOLOGÍA PEDIÁTRICA Y ESTRABISMO',
            'ONCOLOGÍA CLÍNICA',
            'ONCOLOGÍA PEDIÁTRICA',
            'ONCOLOGÍA QUIRÚRGICA',
            'ONCOLOGÍA RADIOTERÁPICA',
            'OPTOMETRÍA',
            'ORTODONCIA Y ORTOPEDIA MAXILAR',
            'ORTOPEDIA ONCOLÓGICA',
            'ORTOPEDIA Y TRAUMATOLOGÍA',
            'OTORRINOLARINGOLOGÍA Y CIRUGÍA DE CABEZA Y CUELLO',
            'PATOLOGÍA CLÍNICA Y ANATÓMICA',
            'PATOLOGÍA MOLECULAR',
            'PEDIATRÍA DE EMERGENCIAS Y DESASTRES',
            'PERFUSIÓN EXTRACORPÓREA, CIRUGÍA CARDIACA Y VASCULAR',
            'PERIODONCIA E IMPLANTOLOGÍA',
            'PERITAJE JUDICIAL',
            'PREVENCIÓN DE CANCER GINECOLÓGICO',
            'PROMOCIÓN DE LA SALUD MATERNA CON MENCIÓN EN PSICOPROFILAXIS OBSTÉTRICA Y ESTIMULACIÓN PRENATAL',
            'PROMOCIÓN Y PREVENCIÓN DE ITS-VIH/SIDA Y CÁNCER DE CUELLO UTERINO',
            'PROYECTOS DE DESARROLLO SOCIAL',
            'PSICOGERIATRÍA',
            'PSICOLOGÍA CLÍNICA Y DE LA SALUD',
            'PSICOLOGÍA DE LAS ADICCIONES',
            'PSICOLOGÍA DE LAS EMERGENCIAS Y DESASTRES',
            'PSICOLOGÍA DEL ADULTO MAYOR',
            'PSICOLOGÍA JURÍDICA',
            'PSICOLOGÍA ORGANIZACIONAL',
            'PSICOLOGÍA PENITENCIARIA',
            'PSICOLOGÍA SOCIAL-COMUNITARIA',
            'PSIQUIATRÍA DE NIÑOS Y ADOLESCENTES',
            'QUIMICA AMBIENTAL Y LEGAL',
            'RADIOLOGÍA INTERVENCIONISTA',
            'RADIOLOGÍA Y DIAGNOSTICO POR IMÁGENES',
            'RECUPERACIÓN POS ANESTÉSICA Y TRATAMIENTO DEL DOLOR',
            'RECURSOS VEGETALES TERAPEUTICOS',
            'REHABILITACIÓN ORAL',
            'RESPONSABILIDAD SOCIAL',
            'REUMATOLOGÍA',
            'RINOLOGÍA',
            'SALUD FAMILIAR Y COMUNITARIA EN ODONTOLOGÍA',
            'SALUD OCUPACIONAL E HIGIENE DEL AMBIENTE LABORAL',
            'SALUD PÚBLICA CON MENCIÓN EN EPIDEMIOLOGIA',
            'SALUD PÚBLICA ESTOMATOLÓGICA',
            'SALUD SEXUAL Y REPRODUCTIVA DEL ESCOLAR Y ADOLESCENTE',
            'SEGURIDAD ALIMENTARIA',
            'SEGURIDAD Y SALUD EN EL TRABAJO',
            'SOPORTE NUTRICIONAL FARMACOLÓGICO',
            'TANATOLOGÍA SOCIAL',
            'TECNICO ESPECIALIZADO EN LABORATORIO CLINICO',
            'TECNICO ESPECIALIZADO EN TERAPIA FISICA Y REHABILITACION',
            'TERAPÉUTICAS ALTERNATIVAS Y FARMACOLOGÍA VEGETAL',
            'TERAPIA COGNITIVO CONDUCTUAL',
            'TERAPIA ENDOVASCULAR NEUROLÓGICA',
            'TERAPIA FAMILIAR SISTEMÁTICA',
            'TOCOGINECOLOGÍA',
            'TOXICOLOGÍA Y CONTROL ALIMENTARIO',
            'TRABAJO SOCIAL CLÍNICO',
            'TRABAJO SOCIAL EMPRESARIAL',
            'TRABAJO SOCIAL EN EL ÁMBITO DE LA GESTIÓN DE RIESGOS DESASTRES',
            'TRABAJO SOCIAL SALUD Y COMUNIDAD',
            'UROLOGÍA GENERAL Y ONCOLÓGICA',
            'VIOLENCIA FAMILIAR, VIOLENCIA Y GÉNERO Y DERECHOS HUMANOS',
            'VITALIDAD FETAL',
            'SIN ESPECIALIDAD'
        ];

        $data = [];
        $timestamp = date('Y-m-d H:i:s');

        foreach ($especialidadesRaw as $nombre) {
            $data[] = [
                'se_nombre' => $nombre,
                'se_abreviatura' => $this->generarAbreviatura($nombre),
                'se_estado' => 1,
                'created_by' => 1,
                'created_at' => $timestamp
            ];
        }

        // 2. Inserción masiva optimizada por lotes (100 en 100) para proteger la base de datos
        $this->db->table('casis_segunda_especialidad')->insertBatch($data, null, 100);
    }

    /**
     * Helper interno para construir abreviaturas limpias y legibles automáticamente.
     */
    private function generarAbreviatura(string $texto): string
    {
        if ($texto === 'SIN ESPECIALIDAD') {
            return 'S/E';
        }

        // Remover conectores comunes en español para no ensuciar la abreviatura
        $excluir = ['DE', 'EN', 'Y', 'EL', 'LA', 'LOS', 'LAS', 'CON', 'PARA', 'POR', 'MENCIÓN', 'DEL', '-'];

        // Limpiar puntuación y dividir en palabras
        $textoLimpio = str_replace([',', '.', '/', '-'], ' ', $texto);
        $palabras = array_filter(explode(' ', strtoupper($textoLimpio)));

        $filtradas = [];
        foreach ($palabras as $palabra) {
            // Quitar tildes básicas para la comparación
            $palabraPlana = str_replace(['Á', 'É', 'Í', 'Ó', 'Ú'], ['A', 'E', 'I', 'O', 'U'], $palabra);
            if (!in_array($palabraPlana, $excluir)) {
                $filtradas[] = $palabra;
            }
        }

        // Si es una sola palabra grande, toma las primeras 4 letras
        if (count($filtradas) === 1) {
            return substr(reset($filtradas), 0, 4);
        }

        // Si son varias palabras, extrae las primeras letras de las 3 o 4 palabras más importantes
        $abr = '';
        foreach (array_slice($filtradas, 0, 4) as $p) {
            $abr .= substr($p, 0, 1);
        }

        return $abr;
    }
}
