<?php
namespace Modules\Seleccion\Services;
use Modules\Seleccion\Models\FichaEvaluacionModel;
use Modules\Seleccion\Models\CriterioEvaluacionModel;
use Modules\Seleccion\Models\ReglaPuntajeModel;

class FichaEvaluacionService
{
    private FichaEvaluacionModel $fichas; private CriterioEvaluacionModel $criterios; private ReglaPuntajeModel $reglas;
    public function __construct() { $this->fichas=new FichaEvaluacionModel(); $this->criterios=new CriterioEvaluacionModel(); $this->reglas=new ReglaPuntajeModel(); }
    public function fichas(int $conId): array { return $this->fichas->where('fie_con_ide',$conId)->orderBy('fie_nombre')->findAll(); }
    public function guardarFicha(array $d): array { $id=!empty($d['fie_ide'])?(int)$d['fie_ide']:null; if($id && (!$actual=$this->fichas->find($id) || (int)$actual['fie_con_ide'] !== (int)$d['fie_con_ide'])) return $this->error(404,'La ficha no existe en esta convocatoria.'); $r=['fie_con_ide'=>(int)$d['fie_con_ide'],'fie_nombre'=>trim($d['fie_nombre']),'fie_tipo'=>$d['fie_tipo'],'fie_version'=>(int)($d['fie_version']?:1),'fie_estado'=>$d['fie_estado'],'fie_puntaje_maximo'=>(float)$d['fie_puntaje_maximo']]; $id=$id?:$this->fichas->insert($r,true); if(!empty($d['fie_ide']))$this->fichas->update($id,$r); return ['ok'=>true,'code'=>200,'message'=>'Ficha guardada correctamente.','data'=>$this->fichas->find($id)]; }
    public function eliminarFicha(int $id):array { if(!$this->fichas->find($id))return $this->error(404,'La ficha no existe.'); if($this->criterios->where('cri_fie_ide',$id)->countAllResults())return $this->error(409,'No puede eliminar una ficha con criterios activos.'); $this->fichas->delete($id);return ['ok'=>true,'code'=>200,'message'=>'Ficha eliminada correctamente.']; }
    public function criterios(int $fieId):array{return $this->criterios->where('cri_fie_ide',$fieId)->orderBy('cri_orden')->findAll();}
    public function guardarCriterio(array $d):array { $id=!empty($d['cri_ide'])?(int)$d['cri_ide']:null; $ficha=$this->fichas->find((int)$d['cri_fie_ide']);if(!$ficha)return $this->error(404,'La ficha no existe.');if($id && (!$actual=$this->criterios->find($id)||(int)$actual['cri_fie_ide']!==(int)$d['cri_fie_ide']))return $this->error(404,'El criterio no existe en esta ficha.');$puntaje=(float)$d['cri_puntaje_maximo'];$suma=$this->criterios->selectSum('cri_puntaje_maximo')->where('cri_fie_ide',$d['cri_fie_ide']);if($id)$suma->where('cri_ide !=',$id);$usado=(float)(($suma->first()['cri_puntaje_maximo']??0));if($usado+$puntaje>(float)$ficha['fie_puntaje_maximo'])return $this->error(422,'La suma de criterios excede el puntaje maximo de la ficha.');$r=['cri_fie_ide'=>(int)$d['cri_fie_ide'],'cri_codigo'=>trim($d['cri_codigo']??'')?:null,'cri_nombre'=>trim($d['cri_nombre']),'cri_descripcion'=>trim($d['cri_descripcion']??'')?:null,'cri_tipo'=>$d['cri_tipo']??null,'cri_puntaje_maximo'=>$puntaje,'cri_obligatorio'=>isset($d['cri_obligatorio'])?1:0,'cri_orden'=>(int)$d['cri_orden']];$id=$id?:$this->criterios->insert($r,true);if(!empty($d['cri_ide']))$this->criterios->update($id,$r);return ['ok'=>true,'code'=>200,'message'=>'Criterio guardado correctamente.','data'=>$this->criterios->find($id)]; }
    public function eliminarCriterio(int $id):array{if(!$this->criterios->find($id))return $this->error(404,'El criterio no existe.');if($this->reglas->where('rpu_cri_ide',$id)->countAllResults())return $this->error(409,'No puede eliminar un criterio con reglas activas.');$this->criterios->delete($id);return ['ok'=>true,'code'=>200,'message'=>'Criterio eliminado correctamente.'];}
    public function reglas(int $criId):array{return $this->reglas->where('rpu_cri_ide',$criId)->orderBy('rpu_orden')->findAll();}
    public function guardarRegla(array $d):array{$id=!empty($d['rpu_ide'])?(int)$d['rpu_ide']:null;if(!$this->criterios->find((int)$d['rpu_cri_ide']))return $this->error(404,'El criterio no existe.');if($id&&(!$actual=$this->reglas->find($id)||(int)$actual['rpu_cri_ide']!==(int)$d['rpu_cri_ide']))return $this->error(404,'La regla no existe en este criterio.');$min=$d['rpu_valor_min']!==''?(float)$d['rpu_valor_min']:null;$max=$d['rpu_valor_max']!==''?(float)$d['rpu_valor_max']:null;if($min!==null&&$max!==null&&$max<$min)return $this->error(422,'El valor maximo no puede ser menor al minimo.');$r=['rpu_cri_ide'=>(int)$d['rpu_cri_ide'],'rpu_tipo'=>$d['rpu_tipo']??null,'rpu_condicion'=>trim($d['rpu_condicion']??'')?:null,'rpu_valor_min'=>$min,'rpu_valor_max'=>$max,'rpu_puntaje'=>(float)$d['rpu_puntaje'],'rpu_formula'=>trim($d['rpu_formula']??'')?:null,'rpu_orden'=>(int)$d['rpu_orden']];$id=$id?:$this->reglas->insert($r,true);if(!empty($d['rpu_ide']))$this->reglas->update($id,$r);return ['ok'=>true,'code'=>200,'message'=>'Regla guardada correctamente.','data'=>$this->reglas->find($id)];}
    public function eliminarRegla(int $id):array{if(!$this->reglas->find($id))return $this->error(404,'La regla no existe.');$this->reglas->delete($id);return ['ok'=>true,'code'=>200,'message'=>'Regla eliminada correctamente.'];}
    private function error(int $code,string $message):array{return ['ok'=>false,'code'=>$code,'message'=>$message];}
}
