<?php
namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // Menús de CONFIGURACIÓN
            [
                'type' => 'primary',
                'parent_id' => null,
                'name' => 'Configuración',
                'abbr' => null,
                'url' => null,
                'icon' => '',
                'status' => 'active',
                'separator' => null,
                'order' => 510,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 1, // ID del menú 'Configuración'
                'name' => 'Usuarios',
                'abbr' => null,
                'url' => '/configuracion/usuarios',
                'icon' => 'users-group-rounded-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 520,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 1, // ID del menú 'Configuración'
                'name' => 'Menús',
                'abbr' => null,
                'url' => '/configuracion/menus',
                'icon' => 'hamburger-menu-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 530,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 1, // ID del menú 'Configuración'
                'name' => 'Perfiles',
                'abbr' => null,
                'url' => '/configuracion/perfiles',
                'icon' => 'user-id-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 540,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 1, // ID del menú 'Configuración'
                'name' => 'Oficinas',
                'abbr' => null,
                'url' => '/configuracion/oficinas',
                'icon' => 'buildings-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 550,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 1, // ID del menú 'Configuración'
                'name' => 'Documentos',
                'abbr' => null,
                'url' => '/configuracion/documentos',
                'icon' => 'folder-with-files-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 560,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Menús de EXPEDIENTE
            [
                'type' => 'primary',
                'parent_id' => null,
                'name' => 'EXPEDIENTE',
                'abbr' => null,
                'url' => null,
                'icon' => 'fa-folder',
                'status' => 'active',
                'separator' => null,
                'order' => 310,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 7, // ID del menú 'EXPEDIENTE'
                'name' => 'Para Recibir',
                'abbr' => null,
                'url' => '/expediente/para_recibir',
                'icon' => 'inbox-in-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 320,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 7, // ID del menú 'EXPEDIENTE'
                'name' => 'Nuevo trámite',
                'abbr' => null,
                'url' => '/expediente/nuevo',
                'icon' => 'pen-new-square-outline',
                'status' => 'active',
                'separator' => null,
                'order' => 330,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            [
                'type' => 'secondary',
                'parent_id' => 7, // ID del menú 'EXPEDIENTE'
                'name' => 'Enviados',
                'abbr' => null,
                'url' => '/expediente/enviados',
                'icon' => 'file-send-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 340,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Menús de DOCUMENTOS
            [
                'type' => 'primary',
                'parent_id' => null,
                'name' => 'DOCUMENTOS',
                'abbr' => null,
                'url' => null,
                'icon' => 'fa-file',
                'status' => 'active',
                'separator' => null,
                'order' => 410,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 11, // ID del menú 'DOCUMENTOS'
                'name' => 'Emisión de Documentos',
                'abbr' => null,
                'url' => '/documentos/emision',
                'icon' => 'fa-file-export',
                'status' => 'active',
                'separator' => null,
                'order' => 410,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 11, // ID del menú 'DOCUMENTOS'
                'name' => 'Recepción de Documentos',
                'abbr' => null,
                'url' => '/documentos/recepcion',
                'icon' => 'fa-file-import',
                'status' => 'active',
                'separator' => null,
                'order' => 420,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 11, // ID del menú 'DOCUMENTOS'
                'name' => 'Emisión Personal',
                'abbr' => null,
                'url' => '/documentos/emision_personal',
                'icon' => 'fa-user-edit',
                'status' => 'active',
                'separator' => null,
                'order' => 430,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Menús de CONSULTAS
            [
                'type' => 'primary',
                'parent_id' => null,
                'name' => 'CONSULTAS',
                'abbr' => null,
                'url' => null,
                'icon' => 'fa-search',
                'status' => 'active',
                'separator' => null,
                'order' => 210,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 15, // ID del menú 'CONSULTAS'
                'name' => 'Documentos Emitidos',
                'abbr' => null,
                'url' => '/consultas/emitidos',
                'icon' => 'fa-file-alt',
                'status' => 'active',
                'separator' => null,
                'order' => 220,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 15, // ID del menú 'CONSULTAS'
                'name' => 'Documentos Recibidos',
                'abbr' => null,
                'url' => '/consultas/recibidos',
                'icon' => 'fa-file-invoice',
                'status' => 'active',
                'separator' => null,
                'order' => 230,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 15, // ID del menú 'CONSULTAS'
                'name' => 'Documentos Personales',
                'abbr' => null,
                'url' => '/consultas/personales',
                'icon' => 'fa-user',
                'status' => 'active',
                'separator' => null,
                'order' => 240,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 15, // ID del menú 'CONSULTAS'
                'name' => 'Seguimiento de Emitidos',
                'abbr' => null,
                'url' => '/consultas/seguimiento_emitidos',
                'icon' => 'fa-search-plus',
                'status' => 'active',
                'separator' => null,
                'order' => 250,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 15, // ID del menú 'CONSULTAS'
                'name' => 'Seguimiento de Recibidos',
                'abbr' => null,
                'url' => '/consultas/seguimiento_recibidos',
                'icon' => 'fa-search-minus',
                'status' => 'active',
                'separator' => null,
                'order' => 250,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Menús de MESA DE PARTES
            [
                'type' => 'primary',
                'parent_id' => null,
                'name' => 'MESA DE PARTES',
                'abbr' => null,
                'url' => null,
                'icon' => 'fa-deskpro',
                'status' => 'active',
                'separator' => null,
                'order' => 100,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 21, // ID del menú 'MESA DE PARTES'
                'name' => 'Derivados',
                'abbr' => null,
                'url' => '/mesa_de_partes/para_despacho',
                'icon' => 'archive-up-outline',
                'status' => 'active',
                'separator' => null,
                'order' => 120,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 21, // ID del menú 'MESA DE PARTES'
                'name' => 'Observados',
                'abbr' => null,
                'url' => '/mesa_de_partes/observados',
                'icon' => 'archive-broken',
                'status' => 'active',
                'separator' => null,
                'order' => 130,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 21, // ID del menú 'MESA DE PARTES'
                'name' => 'Todos',
                'abbr' => null,
                'url' => '/mesa_de_partes/todos_expediente',
                'icon' => 'inbox-archive-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 140,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 21, // ID del menú 'MESA DE PARTES'
                'name' => 'No leídos',
                'abbr' => null,
                'url' => '/mesa_de_partes/no_leidos',
                'icon' => 'eye-closed-bold',
                'status' => 'active',
                'separator' => null,
                'order' => 110,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // REPORTES
            [
                'type' => 'primary',
                'parent_id' => null,
                'name' => 'REPORTES',
                'abbr' => null,
                'url' => null,
                'icon' => null,
                'status' => 'active',
                'separator' => null,
                'order' => 100,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'type' => 'secondary',
                'parent_id' => 21, // ID del menú 'MESA DE PARTES'
                'name' => 'No leídos',
                'abbr' => null,
                'url' => '/mesa_de_partes/reportes',
                'icon' => 'chart-linear',
                'status' => 'active',
                'separator' => null,
                'order' => 110,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

        ];

        // Insert the data into the 'menus' table
        $this->db->table('menus')->insertBatch($data);
    }
}
